"""The lookup-code vocabulary: short, common words that survive a phone line.

One or two syllables, no proper nouns, and no homophones ("two/to", "eight/ate") --
STT has to get these right from a caller reading them back weeks later. 300 words,
so a three-word code is one of 27 million.
"""

WORDS = (
    "acorn", "alder", "amber", "anchor", "ancient", "apple",
    "aspen", "autumn", "azure", "badger", "bagel", "bamboo",
    "banjo", "basil", "basket", "beach", "beacon", "beaver",
    "beetle", "berry", "birch", "bison", "blanket", "blossom",
    "blue", "bold", "boulder", "bouncy", "branch", "brave",
    "bread", "breeze", "bridge", "bright", "bronze", "brook",
    "bubble", "bucket", "bugle", "bunny", "butter", "button",
    "cabbage", "cabin", "cactus", "camel", "candle", "candy",
    "canyon", "carrot", "castle", "cedar", "cheese", "cherry",
    "chilly", "chimney", "cider", "clever", "cliff", "cloud",
    "clover", "cobalt", "cocoa", "coffee", "comet", "compass",
    "cookie", "copper", "coral", "cottage", "cozy", "crab",
    "crane", "creek", "cricket", "crimson", "crispy", "crunchy",
    "daisy", "dawn", "dizzy", "dolphin", "donkey", "drizzle",
    "dusk", "dusty", "eager", "eagle", "echo", "elm",
    "falcon", "feather", "fern", "ferret", "fiddle", "field",
    "finch", "flute", "fog", "forest", "fox", "frog",
    "frost", "fuzzy", "garden", "garlic", "gecko", "gentle",
    "ginger", "glossy", "goat", "golden", "grape", "grass",
    "gravel", "green", "guitar", "hammer", "happy", "harbor",
    "harp", "hazel", "hedgehog", "hollow", "honey", "horse",
    "island", "ivory", "ivy", "jacket", "jade", "jelly",
    "jolly", "jungle", "kettle", "kite", "kitten", "ladder",
    "ladybug", "lantern", "laurel", "lazy", "leaf", "lemon",
    "leopard", "lettuce", "lily", "lion", "lively", "lizard",
    "llama", "lobster", "lucky", "lynx", "mango", "maple",
    "marble", "meadow", "mellow", "melon", "merry", "mighty",
    "mirror", "mitten", "moose", "moss", "moth", "mountain",
    "muffin", "mushroom", "mustard", "navy", "newt", "noodle",
    "noon", "oak", "ocean", "olive", "onion", "opal",
    "orbit", "orchard", "orchid", "otter", "oven", "owl",
    "oyster", "pancake", "panther", "parrot", "pasta", "peach",
    "peanut", "pebble", "pencil", "penguin", "pepper", "petal",
    "pickle", "picnic", "pillow", "pine", "pocket", "pond",
    "pony", "popcorn", "poppy", "pretzel", "pudding", "pumpkin",
    "puppy", "purple", "puzzle", "quiet", "rabbit", "radish",
    "raven", "ribbon", "ridge", "river", "robin", "rocket",
    "rocky", "ruby", "rugged", "rusty", "saffron", "salmon",
    "salty", "sandal", "sandy", "scarlet", "seed", "shadow",
    "sharp", "shiny", "shrimp", "silky", "silver", "sleepy",
    "smooth", "snail", "snowy", "solid", "sparrow", "spicy",
    "spider", "spring", "spruce", "squash", "squirrel", "stone",
    "storm", "sturdy", "sugar", "summit", "sunny", "sunset",
    "swan", "sweater", "sweet", "swift", "syrup", "tangy",
    "teal", "tender", "thistle", "thunder", "tidy", "tiger",
    "tiny", "toast", "topaz", "tower", "trout", "trumpet",
    "tulip", "tunnel", "turtle", "valley", "velvet", "vivid",
    "waffle", "wagon", "walnut", "walrus", "wasp", "weasel",
    "whistle", "willow", "window", "windy", "winter", "witty",
    "wolf", "wooden", "wren", "yellow", "yogurt", "zebra",
)
